# This is a basic workflow to help you get started with Actions

name: Test01 - Install Emacs

# Controls when the action will run. Triggers the workflow on push orHelpe pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Check available versions
      run: |
        ansible --version
    
    - name: Install ansible roles
      run: |
        ansible-galaxy install marcinpraczko.goss-install

    - name: Display workspace details
      run: |
        id
        who
        pwd
        ls -la

    - name: Install emacs
      run: |
        sudo apt-get update
        sudo apt-get -y install emacs24 
        emacs --version
